# Generated by Django 6.0.7 on 2026-07-23 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Qatar', max_length=64)),
                ('invoice_prefix', models.CharField(default='INV', max_length=12)),
                ('receipt_footer', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='shop-logos/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shops_name_idx'), models.Index(fields=['phone'], name='shops_phone_idx')],
            },
        ),
    ]
