# Generated by Django 6.0.7 on 2026-07-23 11:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Qatar', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('default_tax_rate__gte', 0), ('default_tax_rate__lte', 100)), name='shops_default_tax_rate_range'),
        ),
    ]
