# Generated by Django 6.0.7 on 2026-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shop_shops_email_ci_uniq"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="primary_language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "English"),
                    ("ARABIC", "Arabic"),
                    ("MALAYALAM", "Malayalam"),
                    ("HINDI", "Hindi"),
                    ("URDU", "Urdu"),
                ],
                default="ENGLISH",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="secondary_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ENGLISH", "English"),
                    ("ARABIC", "Arabic"),
                    ("MALAYALAM", "Malayalam"),
                    ("HINDI", "Hindi"),
                    ("URDU", "Urdu"),
                ],
                max_length=12,
            ),
        ),
    ]
