# Generated by Django 6.0.7 on 2026-07-24 04:06

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0002_shop_city_shop_country_shop_default_tax_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balance', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_balances', to='shops.shop')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening stock'), ('STOCK_IN', 'Stock received'), ('STOCK_OUT', 'Stock removed'), ('DAMAGE', 'Damaged'), ('EXPIRED', 'Expired'), ('CORRECTION_IN', 'Correction increase'), ('CORRECTION_OUT', 'Correction decrease')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventorybalance')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['shop', 'quantity_on_hand'], name='inv_shop_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorybalance',
            index=models.Index(fields=['shop', 'low_stock_threshold'], name='inv_shop_threshold_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('shop', 'product'), name='inventory_balance_shop_product_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='inventory_low_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.CheckConstraint(condition=models.Q(('allow_negative_stock', True), ('quantity_on_hand__gte', 0), _connector='OR'), name='inventory_quantity_negative_policy'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['shop', 'product', '-created_at'], name='inv_move_shop_product_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['inventory_balance', '-created_at'], name='inv_move_balance_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['shop', 'movement_type', '-created_at'], name='inv_move_shop_type_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity_delta', 0), _negated=True), ('movement_type', 'OPENING'), _connector='OR'), name='inventory_movement_delta_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after', django.db.models.expressions.CombinedExpression(models.F('quantity_before'), '+', models.F('quantity_delta')))), name='inventory_movement_balances'),
        ),
    ]
