# Generated by Django 6.0.7 on 2026-07-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('OPENING', 'Opening stock'), ('STOCK_IN', 'Stock received'), ('STOCK_OUT', 'Stock removed'), ('DAMAGE', 'Damaged'), ('EXPIRED', 'Expired'), ('CORRECTION_IN', 'Correction increase'), ('CORRECTION_OUT', 'Correction decrease'), ('SALE', 'Sale')], max_length=20),
        ),
    ]
