# Generated by Django 6.0.7 on 2026-07-28 07:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0003_shop_activated_at_shop_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='QAR', max_length=3)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('max_users', models.PositiveIntegerField(default=3)),
                ('max_products', models.PositiveIntegerField(default=500)),
                ('reports_enabled', models.BooleanField(default=True)),
                ('advanced_reports_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['monthly_price', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0), ('yearly_price__gte', 0)), name='saas_plan_prices_nonnegative'), models.CheckConstraint(condition=models.Q(('max_users__gte', 1), ('max_products__gte', 1)), name='saas_plan_limits_positive')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('SHOP_REGISTERED', 'Shop registered'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('ROLE_CHANGED', 'Role changed'), ('PASSWORD_RESET', 'Password reset'), ('SUBSCRIPTION_CHANGED', 'Subscription changed')], db_index=True, max_length=32)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saas_audit_events', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='shops.shop')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_saas_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'created_at'], name='saas_audit_shop_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('CASHIER', 'Cashier')], max_length=10)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'email'], name='saas_inv_shop_email_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('shop'), condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), name='saas_inv_pending_shop_email_uniq'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='saas_invitation_expiry_after_create')],
            },
        ),
        migrations.CreateModel(
            name='ShopSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], db_index=True, default='TRIAL', max_length=16)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('grace_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas.plan')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('trial_ends_at__isnull', True), ('trial_started_at__isnull', True), ('trial_ends_at__gte', models.F('trial_started_at')), _connector='OR'), name='saas_trial_dates_valid')],
            },
        ),
    ]
