# Generated by Django 6.0.7 on 2026-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_alter_auditevent_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event',
            field=models.CharField(choices=[('SHOP_REGISTERED', 'Shop registered'), ('INVITATION_SENT', 'Invitation sent'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('USER_ACTIVATED', 'User activated'), ('USER_DEACTIVATED', 'User deactivated'), ('ROLE_CHANGED', 'Role changed'), ('PASSWORD_RESET', 'Password reset'), ('STAFF_USER_CREATED', 'Staff user created'), ('USER_PROFILE_UPDATED', 'User profile updated'), ('STAFF_PASSWORD_RESET', 'Staff password reset'), ('PASSWORD_CHANGED', 'Password changed'), ('USER_LOGIN', 'User login'), ('USER_LOGOUT', 'User logout'), ('SUBSCRIPTION_CHANGED', 'Subscription changed'), ('SHIFT_OPENED', 'Shift opened'), ('SHIFT_CLOSED', 'Shift closed'), ('BILL_HELD', 'Bill held'), ('BILL_RESUMED', 'Bill resumed'), ('BILL_CANCELLED', 'Bill cancelled'), ('SALE_COMPLETED', 'Sale completed'), ('RECEIPT_REPRINTED', 'Receipt reprinted'), ('CARD_PAYMENT_RECORDED', 'Card payment recorded'), ('DATA_EXPORTED', 'Data exported')], db_index=True, max_length=32),
        ),
    ]
