# Generated by Django 6.0.7 on 2026-07-29 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_amount_tendered_payment_change_due_and_more'),
        ('sales', '0004_sale_held_at_sale_held_by_alter_sale_status_and_more'),
        ('shops', '0004_shop_shops_email_ci_uniq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.cashiershift'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_tendered__isnull', True), ('amount_tendered__gte', 0), _connector='OR'), name='payments_tendered_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('change_due__gte', 0)), name='payments_change_nonnegative'),
        ),
    ]
