# Generated by Django 6.0.7 on 2026-07-23 11:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0002_shop_city_shop_country_shop_default_tax_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='shops.shop')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80, null=True)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('MILLILITRE', 'Millilitre'), ('PACK', 'Pack'), ('BOX', 'Box'), ('CARTON', 'Carton'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('BAG', 'Bag')], default='PIECE', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_tax_inclusive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shops.shop')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['shop', 'is_active', 'display_order'], name='prod_cat_shop_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['shop', 'name'], name='prod_cat_shop_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('shop'), name='products_category_shop_name_ci_uniq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'category'], name='prod_shop_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'name'], name='prod_shop_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'sku'], name='prod_shop_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'barcode'], name='prod_shop_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'is_active'], name='prod_shop_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), models.F('shop'), name='products_product_shop_sku_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('shop', 'barcode'), name='products_product_shop_barcode_uniq'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='products_purchase_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='products_selling_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='products_tax_rate_range'),
        ),
    ]
