# Generated by Django 6.0.7 on 2026-07-29 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0004_shop_shops_email_ci_uniq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='VALIDATED', max_length=20)),
                ('duplicate_strategy', models.CharField(blank=True, choices=[('SKIP', 'Skip'), ('UPDATE', 'Update'), ('CANCEL', 'Cancel')], max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('products_skipped', models.PositiveIntegerField(default=0)),
                ('categories_created', models.PositiveIntegerField(default=0)),
                ('inventory_initialized', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_imports', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_imports', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict)),
                ('normalized_data', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=dict)),
                ('duplicate_fields', models.JSONField(default=list)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='products.product')),
                ('product_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='products.productimport')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='productimport',
            index=models.Index(fields=['shop', '-created_at'], name='prod_import_shop_time_idx'),
        ),
        migrations.AddIndex(
            model_name='productimport',
            index=models.Index(fields=['shop', 'status'], name='prod_import_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productimportrow',
            index=models.Index(fields=['product_import', 'row_number'], name='prod_import_row_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimportrow',
            constraint=models.UniqueConstraint(fields=('product_import', 'row_number'), name='products_import_row_number_uniq'),
        ),
    ]
