# Generated by Django 6.0.7 on 2026-07-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimport_productimportrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimport',
            name='categories_to_create',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='productimport',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimport',
            name='failure_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productimport',
            name='opening_movements_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimport',
            name='warning_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimportrow',
            name='warnings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('PIECE', 'Piece'), ('KG', 'Kilogram'), ('GRAM', 'Gram'), ('LITRE', 'Litre'), ('MILLILITRE', 'Millilitre'), ('PACK', 'Pack'), ('BOX', 'Box'), ('CARTON', 'Carton'), ('BOTTLE', 'Bottle'), ('CAN', 'Can'), ('BAG', 'Bag'), ('CUP', 'Cup'), ('JAR', 'Jar'), ('ROLL', 'Roll'), ('TRAY', 'Tray'), ('TUBE', 'Tube')], default='PIECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimportrow',
            name='errors',
            field=models.JSONField(default=list),
        ),
    ]
