# Generated by Django 6.0.7 on 2026-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_normalize_legacy_product_imports"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product-images/"),
        ),
    ]
