# Generated by Django 6.0.7 on 2026-08-06 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pricing_mode",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("MULTI", "Packet and loose")],
                default="STANDARD",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ProductPacket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("size", models.DecimalField(decimal_places=3, max_digits=15)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packets",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "size"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active", "display_order"],
                        name="prod_packet_product_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "size"),
                        name="products_packet_product_size_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("size__gt", 0)),
                        name="products_packet_size_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)),
                        name="products_packet_price_nonnegative",
                    ),
                ],
            },
        ),
    ]
