# Generated by Django 6.0.7 on 2026-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_pricing_mode_productpacket"),
        ("shops", "0005_shop_primary_language_shop_secondary_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="secondary_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="secondary_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["shop", "secondary_name"], name="prod_shop_sec_name_idx"
            ),
        ),
    ]
