# Generated by Django 6.0.7 on 2026-07-24 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesequence_sale_amount_received_sale_change_due_and_more'),
        ('shops', '0002_shop_city_shop_country_shop_default_tax_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['shop', 'status', '-completed_at'], name='sales_shop_status_done_idx'),
        ),
    ]
