# Generated by Django 6.0.7 on 2026-07-29 06:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_sales_shop_status_done_idx'),
        ('shops', '0004_shop_shops_email_ci_uniq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_held', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HELD', 'Held'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12),
        ),
        migrations.CreateModel(
            name='CashierShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=8)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opening_note', models.CharField(blank=True, max_length=500)),
                ('closing_note', models.CharField(blank=True, max_length=500)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts_opened', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to='shops.shop')),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashiershift'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['shop', 'status', '-opened_at'], name='sales_shift_shop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiershift',
            index=models.Index(fields=['shop', 'cashier', '-opened_at'], name='sales_shift_cashier_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('shop', 'cashier'), name='sales_one_open_shift_per_cashier'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='sales_shift_opening_cash_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cashiershift',
            constraint=models.CheckConstraint(condition=models.Q(('counted_closing_cash__isnull', True), ('counted_closing_cash__gte', 0), _connector='OR'), name='sales_shift_counted_cash_nonnegative'),
        ),
    ]
