# Generated by Django 6.0.7 on 2026-08-01 04:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_held_at_sale_held_by_alter_sale_status_and_more"),
        ("shops", "0004_shop_shops_email_ci_uniq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("NONE", "No discount"),
                    ("PERCENTAGE", "Percentage"),
                    ("FIXED", "Fixed amount"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="sales_discount_value_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("discount_type", "PERCENTAGE"), _negated=True),
                    ("discount_value__lte", 100),
                    _connector="OR",
                ),
                name="sales_discount_percentage_max_100",
            ),
        ),
    ]
