# Generated by Django 6.0.7 on 2026-08-06 14:57

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_stock_quantity(apps, schema_editor):
    """Every pre-existing line is a STANDARD line, where the charged quantity
    and the stock-deducted quantity are the same number."""
    SaleItem = apps.get_model("sales", "SaleItem")
    SaleItem.objects.update(stock_quantity=F("quantity"))


def noop(apps, schema_editor):
    """Reversing only drops the column, so there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product_pricing_mode_productpacket"),
        ("sales", "0005_sale_discount_type_sale_discount_value_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="saleitem",
            name="sales_item_sale_product_uniq",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="packet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="products.productpacket",
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="packet_size",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PACKET", "Packet"),
                    ("LOOSE", "Loose"),
                ],
                default="STANDARD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        # Added nullable, backfilled, then tightened: the column is NOT NULL in
        # the final schema, but existing rows need a value before that can hold.
        migrations.RunPython(backfill_stock_quantity, noop),
        migrations.AlterField(
            model_name="saleitem",
            name="stock_quantity",
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("packet__isnull", True)),
                fields=("sale", "product", "pricing_mode"),
                name="sales_item_sale_product_mode_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("packet__isnull", False)),
                fields=("sale", "product", "packet"),
                name="sales_item_sale_product_packet_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("packet__isnull", False), ("pricing_mode", "PACKET")),
                    models.Q(
                        models.Q(("pricing_mode", "PACKET"), _negated=True),
                        ("packet__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="sales_item_packet_matches_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gt", 0)),
                name="sales_item_stock_quantity_positive",
            ),
        ),
    ]
