# Generated by Django 6.0.7 on 2026-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_remove_saleitem_sales_item_sale_product_uniq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="secondary_product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
